In [7]:
# Fair coin implementation
import numpy as np
def faircoin():
    return np.random.uniform(0,1)
n=int(input("Enter number of trials"))
count=0
for i in range(n):
    if faircoin()<=0.5:
        count+=1
print("Prob of head is ",count/n)
print("prob of tails is ",1-(count/n))
    



Enter number of trials10000
Prob of head is  0.4995
prob of tails is  0.5005


In [15]:
#2 program to solve system of linear equations
import numpy as np

n=int(input("Enter order of matrix A"))
matA=[]
matA=input("Enter matrix elements rowwise").split()
matA1=[]
for i in matA:
    matA1.append(int(i))
matA1=np.array(matA1)    
matA1.reshape(n,n)
matB=[]
matB=input("Enter elements of B").split()
matB1=[]
for i in matB:
    matB1.append(int(i))
matB1=np.array(matB1)
matB1.reshape(n,1)
if np.linalg.matrix_rank(matA1)!=np.linalg.matrix_rank(matB1):
    print("No solution")
elif np.linalg.matrix_rank(matA1)<n:
    print("Infinite solutions")
else:
    matX=np.linalg.dot(np.linalg.inv(matA1),matB1)
    print("Unique solution is ",matX)

    


Enter order of matrix A3
Enter matrix elements rowwise1 4 7 8 5 2 3 6 9 
Enter elements of B2 5 8 
Infinite solutions


In [26]:
#3 program to generate two random matrices and create

Ra = int(input("Enter the number of rows:")) 
Ca = int(input("Enter the number of columns:"))   # take the matrices A and B from user
matrixa = [] 
print("Enter the entries rowwise:") 
for i in range(Ra):          # A for loop for row entries 
    a =[] 
    for j in range(Ca):      # A for loop for column entries 
         a.append(np.random.randint(1,50))
    matrixa.append(a) 
for i in range(Ra): 
    for j in range(Ca): 
        print(matrixa[i][j], end = " ") 
    print() 

np.savetxt("MatA.txt",matrixa, fmt="%s")
Rb = int(input("Enter the number of rows:")) 
Cb = int(input("Enter the number of columns:"))   
matrixb = [] 
print("Enter the entries rowwise:") 
for i in range(Rb):          
    r =[] 
    for j in range(Cb):      
         r.append(np.random.randint(1,50)) 
    matrixb.append(r)  
for i in range(Rb): 
    for j in range(Cb): 
        print(matrixb[i][j], end = " ") 
    print()  
np.savetxt("MatB.txt", matrixb, fmt="%s")
if Ra==Rb and Ca==Cb:
    sum_mat=np.add(matrixa,matrixb)
    sub_mat=np.subtract(matrixa,matrixb)
    print("the sum of matrices is:\n",sum_mat)
    print("the subtraction of matrices is:\n",sub_mat)   
else:
    print("operation cannot be performed")
if Ca==Rb:
    mul_mat=np.dot(matrixa,matrixb)
    print("the multiplication matrix is:\n",mul_mat)
else:
    print("We cannot perform multiplication:\n")
    

Enter the number of rows:2
Enter the number of columns:2
Enter the entries rowwise:
31 24 
27 46 
Enter the number of rows:2
Enter the number of columns:2
Enter the entries rowwise:
14 14 
21 11 
the sum of matrices is:
 [[45 38]
 [48 57]]
the subtraction of matrices is:
 [[17 10]
 [ 6 35]]
the multiplication matrix is:
 [[ 938  698]
 [1344  884]]


In [27]:
#4
import random 
def printArray(stream,n): 
    for i in range(n): 
        print(stream[i],end=" ") 
    print()  
def selectKItems(stream, n, k):                   # A function to randomly select 
        i=0                                       # k items from stream[0..n-1].           
        rand_array = [0]*k;                         # index for elements  in stream[] 
        for i in range(k):                         # rand_array[] is the output 
            rand_array[i] = stream[i];              # array. Initialize it with  first k elements from stream[]        
        print(rand_array) 
        while(i < n):                           # Iterate from the (k+1)th 
                j = random.randrange(i+1)        # Pick a random index from 0 to i. 
                print(j)
                if(j < k): 
                    rand_array[j] = stream[i]        # If the randomly picked index is smaller than k, then replace the element 
                i+=1                                #present at the index 
        print("Following are k randomly selected items") 
        printArray(rand_array, k) 
stream = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12] 
n = len(stream); 
k = 5 
selectKItems(stream, n, k) 
  

[1, 2, 3, 4, 5]
0
5
3
6
6
9
0
10
Following are k randomly selected items
11 2 3 7 5 
